#redis:6.0-rc3-alpine
version: "3.8"
services:
  catmashredis:
    image : redis:6.0-rc3-alpine
    privileged: true
    networks: 
      - overlay

  catmashback:
    build : ./back
    container_name: "catmashback"
    depends_on:
      - catmashredis
    env_file:
      - ./back/.env
    networks: 
      - overlay
    ports:
      - "6548:6548"

  catmashfront:
    build : ./front
    container_name: "catmashfront"
    links:
      - catmashback
    depends_on:
      - catmashredis
      - catmashback
    ports:
      - 14525:80

networks:
  overlay:
    ipam:
      driver: default
      config:
          - subnet: 172.16.2.0/30
            gateway: 172.16.2.1
