#redis:6.0-rc3-alpine
version: "3.8"
services:
  catmashredis:
    image : redis:6.0-rc3-alpine
    privileged: true
    networks:
      cluster:
        ipv4_address: 172.100.30.3

  catmashback:
    build : ./back
    container_name: "catmashback"
    depends_on:
      - catmashredis
    env_file:
      - ./back/.env
    ports:
      - "6548:6548"
    networks:
      cluster:
        ipv4_address: 172.100.30.2
    extra_hosts:
      - "catmashredis:172.100.30.3"

  catmashfront:
    build : ./front
    container_name: "catmashfront"
    links:
      - catmashback
    depends_on:
      - catmashredis
      - catmashback
    ports:
      - 14525:80

networks:
  cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.30.0/24
          gateway: 172.100.30.1