apiVersion: apps/v1
kind: Deployment
metadata:
  name: catmash-deployment
spec:
  selector:
    matchLabels:
      app: catmash
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: catmash
    spec:
      containers:
      - name: redis
        image: redis:6.0-rc3-alpine
      - name: back
        image: maissacrement/catmash-back
        env:
        - name: PORT
          value: '6548'
        - name: REDIS_ADDRESS
          value: catmash-service
      - name: front
        image: maissacrement/catmash-front
---
apiVersion: v1
kind: Service
metadata:
  name: catmash-service
spec:
  type: NodePort
  selector:
    app: catmash
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: back
    port: 6548
    targetPort: 6548
    nodePort: 30654