apiVersion: apps/v1
kind: Deployment
metadata:
  name: catmash-deployment
spec:
  selector:
    matchLabels:
      app: catmash
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: catmash
    spec:
      containers:
      - name: redis
        image: redis:6.0-rc3-alpine
        ports:
        - containerPort: 6379
      - name: back
        image: maissacrement/catmash-back
        env:
        - name: PORT
          value: '6548'
        - name: REDIS_ADDRESS
          value: private-network
        ports:
        - containerPort: 6548
      - name: front-end
        image: maissacrement/catmash-front
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catmash-service
spec:
  type: NodePort
  selector:
    app: catmash
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: back
    port: 6548
    targetPort: 6548
    nodePort: 30654
---
apiVersion: v1
kind: Service
metadata:
  name: private-network
spec:
  type: ClusterIP
  selector:
    app: catmash
  ports:
  - name: redis
    port: 6379
    targetPort: 6379